name: bucket_buddies_frontend
description: "Bucket Buddies app for ACM Projects"


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Baloo
      fonts:
        - asset: assets/Baloo-Regular.ttf
    - family: LuckiestGuy
      fonts:
        - asset: fonts/LuckiestGuy-Regular.ttf
    - family: LatoRegular
      fonts:
        - asset: fonts/Lato-Regular.ttf



  uses-material-design: true
  assets:
    - assets/images/BB_Email_Icon.png
    - assets/images/BB_Password_Icon.png
    - assets/images/BB_Hide_Password_Icon.png
    - assets/images/BB_Add_Group.png
    - assets/images/BB_Nav_Home.png
    - assets/images/BB_Nav_Messages.png
    - assets/images/BB_Nav_Profile.png
    - assets/images/BB_Nav_Calendar.png
    - assets/images/BB_Example_Pfp.png
    - android/app/src/main/res/drawable/bb_splash_screen.png
    - assets/BucketBuddiesLogo.png


