name: bucket_buddies_frontend
description: "Bucket Buddies app for ACM Projects"


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/BucketBuddiesLogo.png

  fonts:
     - family: LuckiestGuy
       fonts:
         - asset: fonts/LuckiestGuy-Regular.ttf
     - family: AcmeRegular
       fonts:
         - asset: fonts/Acme-Regular.ttf

