// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoF4i0rK_OxlNb_qAeKl-cNXsUZVkv60s',
    appId: '1:781525005266:web:c107976d8a9a56e475ce0b',
    messagingSenderId: '781525005266',
    projectId: 'bucket-buddies-34fb8',
    authDomain: 'bucket-buddies-34fb8.firebaseapp.com',
    storageBucket: 'bucket-buddies-34fb8.appspot.com',
    measurementId: 'G-H5N6NDBKC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKXP8cLyjOXOGWJXmeoAtBlQs7tY_TulQ',
    appId: '1:781525005266:android:cb95bfceca0ff37175ce0b',
    messagingSenderId: '781525005266',
    projectId: 'bucket-buddies-34fb8',
    storageBucket: 'bucket-buddies-34fb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjPr1i3cBlr43ZEOKcx_SCN6Wth-_0Q5I',
    appId: '1:781525005266:ios:efc3bd3cdef30a8d75ce0b',
    messagingSenderId: '781525005266',
    projectId: 'bucket-buddies-34fb8',
    storageBucket: 'bucket-buddies-34fb8.appspot.com',
    iosBundleId: 'com.example.bucketBuddiesFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjPr1i3cBlr43ZEOKcx_SCN6Wth-_0Q5I',
    appId: '1:781525005266:ios:8de44c42e89ae8cf75ce0b',
    messagingSenderId: '781525005266',
    projectId: 'bucket-buddies-34fb8',
    storageBucket: 'bucket-buddies-34fb8.appspot.com',
    iosBundleId: 'com.example.bucketBuddiesFrontend.RunnerTests',
  );
}
